server:
  port: 3030
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: ADMIN123
    url: jdbc:oracle:thin:@localhost:1521/ORCL2
    username: ADMIN
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
login-app:
  messages: 
    sucess : SUCESS
    accountislocked : ACCOUNT IS LOCKED
    invalidcredentials : INVALID CREDENTIALS
